version: '3.8'

services:
  postgres:
    container_name: postgres_TODO
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ToDo
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_TODO
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"